// sync-assets.mjs — runs before every build and before `next dev`.
//
// Two jobs, both about removing a class of mistake rather than adding a feature.
//
// 1. The editor's starting buffer and the read-only header tabs are generated
//    from the REAL files in engine/. The spec requires the editor buffer to be
//    identical to src/engine.cpp in the boilerplate zip; copying it by hand is
//    how those two silently diverge, and a participant who pastes between them
//    would be the one to find out.
//
// 2. Monaco is copied into public/ and loaded from there. @monaco-editor/react
//    fetches it from a CDN by default, which would mean the editor — the SOLE
//    submission path — stops working if the room's network does. The event runs
//    on three nodes we control; nothing user-facing should depend on jsdelivr.

import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { marked } from 'marked';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const web = resolve(here, '..');
const engine = resolve(web, '../../engine');
const spec = resolve(web, '../../spec');

const HEADERS = ['wire.h', 'order.h', 'out.h', 'engine.h'];

function ts(value) {
  return JSON.stringify(value);
}

async function generateBoilerplate() {
  const skeleton = await readFile(join(engine, 'boilerplate/src/engine.cpp'), 'utf8');

  const headers = {};
  for (const name of HEADERS) {
    headers[name] = await readFile(join(engine, 'include/mebench', name), 'utf8');
  }

  let specText = '';
  try {
    specText = await readFile(join(spec, 'SPEC.md'), 'utf8');
  } catch {
    specText = '# SPEC.md not found at build time';
  }

  // Rendered here rather than in the browser: the spec is a build-time asset
  // generated from our own repo, so shipping a markdown parser to every
  // participant to re-parse a file we already have would be work for nothing.
  const specHtml = marked.parse(specText, { async: false, gfm: true });

  const out = `// GENERATED by scripts/sync-assets.mjs — do not edit.
//
// Regenerated on every build from engine/boilerplate/src/engine.cpp and the
// frozen headers, so the editor buffer and the zip cannot drift apart.

export const STARTING_BUFFER = ${ts(skeleton)};

export const HEADERS: Record<string, string> = ${ts(headers)};

export const HEADER_NAMES = ${ts(HEADERS)} as const;

export const SPEC_MARKDOWN = ${ts(specText)};

export const SPEC_HTML = ${ts(specHtml)};
`;
  await mkdir(join(web, 'lib'), { recursive: true });
  await writeFile(join(web, 'lib/boilerplate.generated.ts'), out);
  console.log(
    `sync-assets: engine.cpp (${skeleton.length}B), ${HEADERS.length} headers, spec (${specText.length}B)`,
  );
}

async function vendorMonaco() {
  const from = join(web, 'node_modules/monaco-editor/min/vs');
  const to = join(web, 'public/monaco/vs');
  await mkdir(dirname(to), { recursive: true });
  await cp(from, to, { recursive: true });
  console.log('sync-assets: monaco vendored to public/monaco/vs (no CDN at runtime)');
}

await generateBoilerplate();
await vendorMonaco();
